### ISSUE TITLE
Where is "riscv_machine.h"?

### ISSUE THREAD

**Issue by huangliwood** [whutddk/Rift2Core#14]
diff include this lib,but I didn't found where is it .

**Comment by whutddk** [comment]
@huangliwood  The `riscv_machine.h` belongs to [dromajo](https://github.com/chipsalliance/dromajo.git), a reference model of RISCV-64. As the doc of the project is out-of-date, you can follow the [docker script](src/docker/dromajo.do) to install the *dromajo* at local and add the library into your environment.

----------------------

By the way:
* I found that the **chipsalliance** has updated the *dromajo* recently, after a few years. Please know that I am using the commit ID: `3675ba09996dbe24286af45a969443a0ee3cfe6e`
* Allowed by definition, the implementation of Rift2Core does not exactly match the model of **dromajo** . **dromajo** is just used to terminate the simulator in a common situation when an error occurs. As a result, don't be surprised if **dromajo** failed in some `riscv-test`, especially in `CSR` and `Privilege` tests.

----------------------

**Comment by whutddk** [comment]
Feel free to reopen it if you have any more question.
