### ISSUE TITLE
why coremark score only 2.xx？is there anything wrong when running coremark program？

### ISSUE THREAD

**Issue by Jeremy-Jia** [whutddk/Rift2Core#15]
2.xx coremark score is suitable for a 2~3 stage single issue in-order pipeline

**Comment by whutddk** [comment]
Thank you for your interest in this project. I develop and maintain this project alone to learn CPU development, and it was my first time. So there must be a lot of incorrect designs in the project.

-----------------------------------------

For the reason why the coremark score is so low:
* Only Rift2370 is configured correctly for performance
* Rift2330 is configured for functional correctness testing, which has minimum size of cache, buff, fifo and so on.
* Rift2300, Rift2310, Rift2320 are configured for taping out at [Efabless](https://efabless.com/), they are configured as single issue, and they had a lot of functionality removed to meet the area requirements for tapeout
* The size of buff, fifo, cache in the other version have not been well configured
* Also, the branch prediction module does not work well. For Rift2370, the prediction accuracy is only 88% in coremark. That's what I will deal with next(if I have time).

**Comment by whutddk** [comment]
Feel free to re-open it if you have any more question.
